In [1]:
import numpy as np

In [2]:
lst1 = [1,2,3,4,5]

In [3]:
arr1 = np.array(lst1)

In [4]:
arr2 = np.array(arr1)

In [5]:
arr3 = np.asarray(arr1)

In [6]:
arr4= np.asanyarray(arr1)

In [7]:
arr1[0]=6

In [8]:
arr1

array([6, 2, 3, 4, 5])

In [9]:
arr2

array([1, 2, 3, 4, 5])

In [10]:
arr3

array([6, 2, 3, 4, 5])

In [11]:
arr4

array([6, 2, 3, 4, 5])

In [12]:
type(arr1)

numpy.ndarray

In [13]:
type(arr2)

numpy.ndarray

In [14]:
type(arr3)

numpy.ndarray

In [15]:
type(arr4)

numpy.ndarray

In [16]:
lst2=[2,3,4,5,6,7,8]

In [17]:
arrx = np.array(lst2)
arry = np.asarray(lst2)
arrz= np.asanyarray(lst2)

In [18]:
print(type(arrx))
print(type(arry))
print(type(arrz))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [19]:
x=np.array([lst2])

In [20]:
x

array([[2, 3, 4, 5, 6, 7, 8]])

In [22]:
id(x[0])

140493153339552

In [23]:
id(x)

140493153255056

In [9]:
np.fromfunction(lambda i,j : i==j ,(3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [10]:
iterable = (1,2,3,4)

In [11]:
type(iterable)

tuple

In [15]:
np.fromiter(iterable,float)

array([1., 2., 3., 4.])

In [16]:
np.fromiter(iterable,int)

array([1, 2, 3, 4])

In [19]:
np.fromstring("124 45",sep=" ",dtype=int)

array([124,  45])

In [20]:
type(np.arange(1,2))

numpy.ndarray

In [22]:
np.arange(7)

array([0, 1, 2, 3, 4, 5, 6])

In [25]:
np.arange(1,6)

array([1, 2, 3, 4, 5])

In [24]:
np.arange(1)

array([0])

In [26]:
np.arange(1,4,2)

array([1, 3])

In [29]:
np.arange(50,-1,5)

array([], dtype=int64)

In [30]:
np.arange(50,-1,-5)

array([50, 45, 40, 35, 30, 25, 20, 15, 10,  5,  0])

In [32]:
#linspace = linearly spaced 

np.linspace(1,4,30)

array([1.        , 1.10344828, 1.20689655, 1.31034483, 1.4137931 ,
       1.51724138, 1.62068966, 1.72413793, 1.82758621, 1.93103448,
       2.03448276, 2.13793103, 2.24137931, 2.34482759, 2.44827586,
       2.55172414, 2.65517241, 2.75862069, 2.86206897, 2.96551724,
       3.06896552, 3.17241379, 3.27586207, 3.37931034, 3.48275862,
       3.5862069 , 3.68965517, 3.79310345, 3.89655172, 4.        ])

In [35]:
np.zeros(3)

array([0., 0., 0.])

In [36]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [37]:
np.ones(7)

array([1., 1., 1., 1., 1., 1., 1.])

In [38]:
np.ones((2,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [39]:
#creates an empty matrix of the size mentioned
np.empty(3)

array([0., 0., 0.])

In [40]:
#creates an identity matrix 
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [41]:
np.arange(8).reshape(2,4)

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [44]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [45]:
np.diag(np.arange(9).reshape(3,3))

array([0, 4, 8])

In [46]:
np.diag(np.arange(9).reshape(3,3),k=2)

array([2])

In [47]:
np.diag(np.arange(9).reshape(3,3),k=1)

array([1, 5])

In [48]:
np.diag(np.arange(9).reshape(3,3),k=0)

array([0, 4, 8])

In [49]:
np.diag(np.arange(9).reshape(3,3),k=-1)

array([3, 7])

In [50]:
np.diag(np.arange(9).reshape(3,3),k=-2)

array([6])

In [51]:
np.diagflat([[1,2], [3,4]])

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [54]:
np.diagflat([1,2], 1)

array([[0, 1, 0],
       [0, 0, 2],
       [0, 0, 0]])

In [55]:
np.tri(3, 5, 1, dtype=int)

array([[1, 1, 0, 0, 0],
       [1, 1, 1, 0, 0],
       [1, 1, 1, 1, 0]])

In [56]:
np.tril([[1,2,3],[4,5,6],[7,8,9]], 0)

array([[1, 0, 0],
       [4, 5, 0],
       [7, 8, 9]])

In [57]:
np.triu([[1,2,3],[4,5,6],[7,8,9],[10,11,12]], 1)

array([[0, 2, 3],
       [0, 0, 6],
       [0, 0, 0],
       [0, 0, 0]])

In [58]:
np.triu([[1,2,3],[4,5,6],[7,8,9],[10,11,12]], 0)

array([[1, 2, 3],
       [0, 5, 6],
       [0, 0, 9],
       [0, 0, 0]])

In [59]:
np.random.rand(6)

array([0.22529393, 0.60102712, 0.37289035, 0.09605413, 0.54254461,
       0.50550342])

In [60]:
np.random.randn(6)

array([ 0.06700549,  2.28644226,  1.62042503, -0.21896273, -1.26268958,
       -0.05332746])

In [61]:
np.random.rand(6,2)

array([[0.55207708, 0.10920518],
       [0.22960481, 0.45378251],
       [0.76644403, 0.99491948],
       [0.09684027, 0.78617447],
       [0.08854119, 0.79362166],
       [0.32659787, 0.2798846 ]])

In [64]:
np.random.randint(6)

1

In [65]:
np.random.randint(6,10)

9

In [66]:
np.random.randint(1,10,(3,3))

array([[5, 8, 3],
       [1, 6, 4],
       [6, 2, 2]])

In [67]:
np.random.randint(1,10,[3,3])

array([[3, 5, 6],
       [9, 1, 7],
       [3, 1, 1]])

In [70]:
np.random.randint(1,10,3)

array([3, 1, 6])

In [ ]:
np.sort()

In [77]:
from numpy.random import randint as ri
mat = np.array(ri(10,100,15)).reshape(3,5)


In [78]:
mat

array([[79, 16, 19, 56, 95],
       [85, 17, 95, 89, 53],
       [27, 75, 53, 65, 11]])

In [79]:
#subsetting 
mat>50

array([[ True, False, False,  True,  True],
       [ True, False,  True,  True,  True],
       [False,  True,  True,  True, False]])

In [80]:
mat[mat>50]

array([79, 56, 95, 85, 95, 89, 53, 75, 53, 65])